### ISSUE TITLE
feat: Endpoint to upload a file

### ISSUE THREAD

**Issue by MiguelMRojas** [hawks-atlanta/proxy-python#18]

**Comment by PedroChaparro** [comment]
- [x] Ready in the SOAP service ([gateway-java/#42](https://github.com/hawks-atlanta/gateway-java/pull/42))

**Comment by andre154** [comment]
Hi! I have a question, I am reviewing both API specifications (.NET and Python) and I want to confirm which fields this endpoint receives, I ask this because in the specifications it is handled in different ways.

upload_file fields
-file
-fileName
-location

Are these fields correct? or am I forgetting someone field?

**Comment by PedroChaparro** [comment]
> Are these fields correct? or am I forgetting someone field?

Hi 👋! Those fields are correct. You can check the [updated specification](https://github.com/hawks-atlanta/proxy-python/blob/dev/docs/spec.openapi.yaml) in the `dev` branch. The problem is that, as you said, this specification is not fully compatible with the .net one, but that shouldn't be a problem if we manage to complete this proxy completely.

I'm doubting about the `fileName` field. If you're able to obtain the name from the file itself, feel free to remove the `fileName` field from the openapi specification.

Also, keep in mind that, right now, the endpoint expects the data to be sent in `multipart/form-data` instead of `application/json`, that's because using `multipart/form-data` you can send a file without encoding it in base64 or any other encoding.
